[package]
name = "hangman"
version = "0.1.0"
edition = "2021"

[dependencies]

[lints.clippy]
# No * imports
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
unwrap_used = "warn"
